In [1]:
import pandas as pd
import numpy as np

In [ ]:
#딕셔너리로 생성
product_dict = {
    'product_name': ['노트북', '마우스', '키보드', '모니터'],
    'price': [1200000, 25000, 80000, 350000],
    'stock': [10, 50, 30, 15],
    'category': ['전자제품', '주변기기', '주변기기', '전자제품']
}


=== 딕셔너리로부터 생성 ===
  product_name    price  stock category
0          노트북  1200000     10     전자제품
1          마우스    25000     50     주변기기
2          키보드    80000     30     주변기기
3          모니터   350000     15     전자제품


In [ ]:
# 데이타프레임 생성
# pd.DataFrame(data,index,columns,dtype)
df_from_dict = pd.DataFrame(product_dict)
print("=== 딕셔너리로부터 생성 ===")
print(df_from_dict)

=== 딕셔너리로부터 생성 ===
  product_name    price  stock category
0          노트북  1200000     10     전자제품
1          마우스    25000     50     주변기기
2          키보드    80000     30     주변기기
3          모니터   350000     15     전자제품


In [6]:
#리스트로부터 생성
product_list = [
    ['노트북', 1200000, 10, '전자제품'],
    ['마우스', 25000, 50, '주변기기'],
    ['키보드', 80000, 30, '주변기기'],
    ['모니터', 350000, 15, '전자제품']
]
print(product_list)



[['노트북', 1200000, 10, '전자제품'], ['마우스', 25000, 50, '주변기기'], ['키보드', 80000, 30, '주변기기'], ['모니터', 350000, 15, '전자제품']]


In [7]:
df_from_list = pd.DataFrame(
    product_list,
    columns=['product_name', 'price', 'stock', 'category'],
    index=['P001', 'P002', 'P003', 'P004']
)
print("=== 리스트로부터 생성 (인덱스 지정) ===")
print(df_from_list)

=== 리스트로부터 생성 (인덱스 지정) ===
     product_name    price  stock category
P001          노트북  1200000     10     전자제품
P002          마우스    25000     50     주변기기
P003          키보드    80000     30     주변기기
P004          모니터   350000     15     전자제품


In [9]:
# numpy 배열로 부터 생성하는 방법
np_array = np.random.randint(1,100,size = (4,3))
print(np_array)
df_from_numpy = pd.DataFrame(
    np_array,
    columns=['A', 'B', 'C'],
    index=['Row1', 'Row2', 'Row3', 'Row4']
)
print(df_from_numpy)

[[47 81 83]
 [35 37 15]
 [14 78  2]
 [85 88 13]]
       A   B   C
Row1  47  81  83
Row2  35  37  15
Row3  14  78   2
Row4  85  88  13


In [11]:
# 빈데이타 프레임 생성
empty_df = pd.DataFrame(
    columns = ['name','age','city']
)
print(empty_df)

new_data = pd.DataFrame({
    'name': ['김철수', '이영희'],
    'age': [25, 30],
    'city': ['서울', '부산']
})



Empty DataFrame
Columns: [name, age, city]
Index: []


In [12]:
df_combined = pd.concat([empty_df, new_data], ignore_index=True)
print("=== 빈 데이터프레임에 데이터 추가 ===")
print(df_combined)

=== 빈 데이터프레임에 데이터 추가 ===
  name age city
0  김철수  25   서울
1  이영희  30   부산


In [36]:
# 외부파일 불러오기
file_name = 'https://raw.githubusercontent.com/zzhining/python_data_basic2/refs/heads/main/3%EC%9E%A5/sample_products.csv'
print(file_name)
df_csv = pd.read_csv(file_name, encoding='utf-8')
print("=== CSV 파일 불러오기 ===")
print(df_csv)

https://raw.githubusercontent.com/zzhining/python_data_basic2/refs/heads/main/3%EC%9E%A5/sample_products.csv
=== CSV 파일 불러오기 ===
  product_id product_name    price category
0       P001          노트북  1200000     전자제품
1       P002          마우스    25000     주변기기
2       P003          키보드    80000     주변기기
3       P004          모니터   350000     전자제품
4       P005          스피커   120000     주변기기


In [15]:
# 불러오기 시 조건 지정
df_filtered = pd.read_csv(
    file_name,
    encoding='utf-8',
    usecols=['product_name', 'price', 'category'],  # 특정 컬럼만
    nrows=3  # 상위 3행만
)
print("=== 조건을 지정하여 불러오기 ===")
print(df_filtered)

=== 조건을 지정하여 불러오기 ===
  product_name    price category
0          노트북  1200000     전자제품
1          마우스    25000     주변기기
2          키보드    80000     주변기기


In [ ]:
## 데이타 프레임 복사

In [16]:
# 원본 데이터프레임 생성
original_df = pd.DataFrame({
    'name': ['김철수', '이영희', '박민수'],
    'age': [25, 30, 35],
    'salary': [3000, 4000, 5000]
})

print("=== 원본 데이터프레임 ===")
print(original_df)

=== 원본 데이터프레임 ===
  name  age  salary
0  김철수   25    3000
1  이영희   30    4000
2  박민수   35    5000


In [ ]:
# 깊은 복사 vs 참조 복사
# 깊은 복사 : df.copy() - 원본이 바뀌지 않는다.
deep_copy_df = original_df.copy() # 원본이 바뀌지 않는다.

reference_df = original_df

print(deep_copy_df)
print(reference_df)

  name  age  salary
0  김철수   25    3000
1  이영희   31    4000
2  박민수   35    5000
  name  age  salary
0  김철수   25    3000
1  이영희   31    4000
2  박민수   35    5000
  name  age  salary
0  김철수   25    3000
1  이영희   31    4000
2  박민수   35    5000
  name  age  salary
0  김철수   25    3000
1  이영희   31    4000
2  박민수   35    5000


In [24]:
# 특정 아이템을 선택
# deep_copy_df.loc[행,열]
deep_copy_df.loc[0,'salary'] = 3500
print(original_df)
reference_df.loc[1,'age'] = 31
print(deep_copy_df)
print(original_df)
print(reference_df)



  name  age  salary
0  김철수   25    3000
1  이영희   31    4000
2  박민수   35    5000
  name  age  salary
0  김철수   25    3500
1  이영희   31    4000
2  박민수   35    5000
  name  age  salary
0  김철수   25    3000
1  이영희   31    4000
2  박민수   35    5000
  name  age  salary
0  김철수   25    3000
1  이영희   31    4000
2  박민수   35    5000


In [27]:
# numpy copy
arr_org = np.arange(10).reshape(2,5)
arr_copy = arr_org.copy()
print(arr_org)
print(arr_copy)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [ ]:
# 딕셔너리 복사
dict_org = {
    'group1' : {'name' : '김철수', 'age':25}
}

print(dict_org)
dict_copy = dict_org.copy()
print(dict_copy)
dict_copy['group1']['age'] = 30
print(dict_copy)
print(dict_org)


# .copy() : 얕은복사, copy.deepcopy() : 깊은복사


{'group1': {'name': '김철수', 'age': 25}}
{'group1': {'name': '김철수', 'age': 25}}
{'group1': {'name': '김철수', 'age': 30}}
{'group1': {'name': '김철수', 'age': 30}}


In [38]:
# 깊은복사
import copy


dict_org1 = {
    'group1' : {'name' : '김철수', 'age':25}
}

print(dict_org1)
dict_copy1 = copy.deepcopy(dict_org1)
print(dict_copy1)
dict_copy1['group1']['age'] = 30
print(dict_copy1)
print(dict_org1)

{'group1': {'name': '김철수', 'age': 25}}
{'group1': {'name': '김철수', 'age': 25}}
{'group1': {'name': '김철수', 'age': 30}}
{'group1': {'name': '김철수', 'age': 25}}


## 행과 열 삭제


In [3]:
test_data = pd.DataFrame({
    'id': [1, 2, 3, 4, 5, 6],
    'name': ['김철수', '이영희', '박민수', '김철수', '정수진', '이영희'],
    'age': [25, 30, None, 25, 28, 30],
    'city': ['서울', '부산', '대구', '서울', None, '부산'],
    'salary': [3000, 4000, 5000, 3000, 3500, 4000],
    'temp_col': ['임시', '임시', '임시', '임시', '임시', '임시']
})
print("=== 원본 데이터 ===")
print(test_data)

=== 원본 데이터 ===
   id name   age city  salary temp_col
0   1  김철수  25.0   서울    3000       임시
1   2  이영희  30.0   부산    4000       임시
2   3  박민수   NaN   대구    5000       임시
3   4  김철수  25.0   서울    3000       임시
4   5  정수진  28.0  NaN    3500       임시
5   6  이영희  30.0   부산    4000       임시


In [6]:
# 특정 열 삭제
# df.drop()
# axis : 삭제출,(0=행, 1=열)
df_drop_col = test_data.drop('temp_col',axis = 1)
print(' ======== 열삭제 후 =======')

df_drop_cols = test_data.drop(['city','age'],axis = 1)
print(df_drop_col)
print(test_data)

 ======== 열삭제 후 =======
   id name   age city  salary
0   1  김철수  25.0   서울    3000
1   2  이영희  30.0   부산    4000
2   3  박민수   NaN   대구    5000
3   4  김철수  25.0   서울    3000
4   5  정수진  28.0  NaN    3500
5   6  이영희  30.0   부산    4000
   id name   age city  salary temp_col
0   1  김철수  25.0   서울    3000       임시
1   2  이영희  30.0   부산    4000       임시
2   3  박민수   NaN   대구    5000       임시
3   4  김철수  25.0   서울    3000       임시
4   5  정수진  28.0  NaN    3500       임시
5   6  이영희  30.0   부산    4000       임시


In [7]:
# 특정 행 삭제(인덱스 기준) : axis = 0
df_drop_row = test_data.drop([0,5],axis = 0)
print(df_drop_row)

   id name   age city  salary temp_col
1   2  이영희  30.0   부산    4000       임시
2   3  박민수   NaN   대구    5000       임시
3   4  김철수  25.0   서울    3000       임시
4   5  정수진  28.0  NaN    3500       임시


In [ ]:
# 중복행 삭제 (keep = 'fist':첫번째(기본값), keep = 'last':마지막,k=False: 중복된 모두)
# duplicates = test_data.drop_duplicates(subset=[컬럼명,'age'],keep= 'False')
df_no_duplicates = test_data.drop_duplicates(subset=['name','age'],keep= False)
print(df_no_duplicates)

   id name   age city  salary temp_col
2   3  박민수   NaN   대구    5000       임시
4   5  정수진  28.0  NaN    3500       임시


In [20]:
# 결측치 삭제(NaN:not a number)
print(test_data)
df_no_na = test_data.dropna()
print(df_no_na)

   id name   age city  salary temp_col
0   1  김철수  25.0   서울    3000       임시
1   2  이영희  30.0   부산    4000       임시
2   3  박민수   NaN   대구    5000       임시
3   4  김철수  25.0   서울    3000       임시
4   5  정수진  28.0  NaN    3500       임시
5   6  이영희  30.0   부산    4000       임시
   id name   age city  salary temp_col
0   1  김철수  25.0   서울    3000       임시
1   2  이영희  30.0   부산    4000       임시
3   4  김철수  25.0   서울    3000       임시
5   6  이영희  30.0   부산    4000       임시


In [ ]:
#특정 columne의 결측치 삭제
print(test_data)
df_no_na_age = test_data.dropna(subset=['age'])

print(df_no_na_age)

   id name   age city  salary temp_col
0   1  김철수  25.0   서울    3000       임시
1   2  이영희  30.0   부산    4000       임시
2   3  박민수   NaN   대구    5000       임시
3   4  김철수  25.0   서울    3000       임시
4   5  정수진  28.0  NaN    3500       임시
5   6  이영희  30.0   부산    4000       임시
   id name   age city  salary temp_col
0   1  김철수  25.0   서울    3000       임시
1   2  이영희  30.0   부산    4000       임시
3   4  김철수  25.0   서울    3000       임시
4   5  정수진  28.0  NaN    3500       임시
5   6  이영희  30.0   부산    4000       임시


In [24]:
# 데이타프레임 생성 
save_data = pd.DataFrame({
    'product_id': ['P001', 'P002', 'P003', 'P004'],
    'product_name': ['노트북', '마우스', '키보드', '모니터'],
    'price': [1200000, 25000, 80000, 350000],
    'category': ['전자제품', '주변기기', '주변기기', '전자제품'],
    'reg_date': pd.date_range('2024-01-01', periods=4, freq='D')
})
print(save_data)

  product_id product_name    price category   reg_date
0       P001          노트북  1200000     전자제품 2024-01-01
1       P002          마우스    25000     주변기기 2024-01-02
2       P003          키보드    80000     주변기기 2024-01-03
3       P004          모니터   350000     전자제품 2024-01-04


In [25]:
#CSV 파일로 저장
save_data.to_csv('products_output.csv',
                 index=False)  # 인덱스 제외
print("\n=== CSV 파일 저장 완료 ===")


=== CSV 파일 저장 완료 ===
