In [ ]:
# NumPy 모듈(라이브러리)
# Numerical Python
# 다차원 배열을 위한 라이브러리
# 다차원 배열인 ndarray를 지원
# 터미널에서 설치 : pip install numpy
# 라브러니 제거 
# 터미널 : pip uninstall numpy
# 코드 : %pip uninstall numpy




In [2]:
%pip install numpy

   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB 660.6 kB/s eta 0:00:20
   ---------------------------------------- 0.1/12.6 MB 1.3 MB/s eta 0:00:10
   - -------------------------------------- 0.3/12.6 MB 2.3 MB/s eta 0:00:06
   - -------------------------------------- 0.5/12.6 MB 3.0 MB/s eta 0:00:05
   -- ------------------------------------- 0.8/12.6 MB 3.4 MB/s eta 0:00:04
   --- ------------------------------------ 1.0/12.6 MB 3.7 MB/s eta 0:00:04
   --- ------------------------------------ 1.2/12.6 MB 3.8 MB/s eta 0:00:03
   ---- ----------------------------------- 1.4/12.6 MB 4.0 MB/s eta 0:00:03
   ----- ---------------------------------- 1.7/12.6 MB 4.2 MB/s eta 0:00:03
   ------ --------------------------------- 1.9/12.6 MB 4.2 MB/s eta 0:00:03
   ------ --------------------------------- 2.2/12.6 MB 4.3 MB/s eta 0:00:03
   ------- 


[notice] A new release of pip is available: 24.0 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [ ]:
# 참고 : from numpy import *
import numpy as np

In [2]:
#리스트 연산 - 반복문 필요 (리스트 항목에 2를 곱하기)
list_data = [1, 2, 3, 4]
result_list = []
for item in list_data:
    result_list.append(item * 2)
print(result_list)

[2, 4, 6, 8]


In [7]:
# 배열 연산 - 벡터화 연산
array_data = np.array([1, 2, 3, 4])
result_array = array_data * 2
print(result_array)

[2 4 6 8]


In [8]:
# np.array() 함수
list1 = [1, 2, 3]
arr1 = np.array(list1)
print(list1)
print(arr1)

[1, 2, 3]
[1 2 3]


In [9]:
import time

In [10]:

# 리스트 연산
start_time = time.time()
python_list = list(range(1000000))
result_list = [x * 2 for x in python_list]
list_time = time.time() - start_time
print(f"리스트 연산 시간: {list_time:.4f}초")


리스트 연산 시간: 0.1448초


In [11]:
# 배열 연산
start_time = time.time()
numpy_array = np.arange(1000000)
result_array = numpy_array * 2
numpy_time = time.time() - start_time
print(f"NumPy 배열 연산 시간: {numpy_time:.4f}초")
print(f"속도 개선: {list_time / numpy_time:.1f}배")

NumPy 배열 연산 시간: 0.0080초
속도 개선: 18.2배


In [14]:
# list를 사용한 연산
start_time = time.time()
# 기준시산이 1970년 1월 1일 00:00:00 (UTC)
print(start_time)
# [0,1,2,,,,,1000000]
python_list = list(range(1000000))
result_list = [x *2 for x in python_list]
# print(result_list)
list_time = time.time() - start_time
print(list_time)


1782355672.927386
0.1822342872619629


In [16]:
#배열을 사용한 연산
start_time = time.time()
print(start_time)
numpy_array = np.arange(1000000)
result_array = numpy_array * 2
print(result_array)
numpy_time = time.time() - start_time
print(f"NumPy 배열 연산 시간: {numpy_time:.6f}초")


1782356131.267309
[      0       2       4 ... 1999994 1999996 1999998]
NumPy 배열 연산 시간: 0.009423초
