# 배열의 생성 및 조작

In [1]:
import numpy as np

In [7]:
list1 = [1, 2, 3]
arr1 = np.array(list1)
arr2 = np.array([1, 2, 3])
print(list1)
print(arr1)
print(arr2)

[1, 2, 3]
[1 2 3]
[1 2 3]


In [17]:
#np.arange()
arr1 = np.arange(10)
print(arr1)
arr2 = np.arange(0,10,1)
print(arr2)
arr2 = np.arange(10,0,-1)
print(arr2)


[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[10  9  8  7  6  5  4  3  2  1]


In [ ]:
# np.array([1, 2, 3, 4, 5]) 생성
# np.arange(1, 6) 생성
# np.zeros(5)
# np.ones(5)
# np.linspace(0, 10, 5)
# np.random.random(5)

In [ ]:
np.ones(3)

array([1., 1., 1.])

In [20]:
np.zeros(5)
np.zeros((2, 3))
np.zeros((2, 3, 4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [23]:
#np.random.rand() - 랜덤값 배열
#0이상~1미만 사이의 무작위 수로 배열
np.random.rand(2, 3)

array([[0.9489172 , 0.49168544, 0.94535787],
       [0.4028819 , 0.23980612, 0.97408828]])

In [27]:
# np.empty()
arr = np.empty((5,2))
print(arr)


[[0.0e+000 4.9e-324]
 [9.9e-324 1.5e-323]
 [2.0e-323 2.5e-323]
 [3.0e-323 3.5e-323]
 [4.0e-323 4.4e-323]]


In [5]:
# 배열 차원 변형
# reshape(형태)
arr2 = np.arange(16)
print(arr2)
arr2.reshape(2, 2, 4)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [ ]:
# 배열 속성 확인 및 타입 변환
# Shape : 각 차원의 크기
# dtype : 배열의 데이터 타입
# astype(타입) : 배열의 데이터 타입 변환

In [6]:
arr2.shape

(16,)

In [7]:
arr2.dtype

dtype('int64')

In [8]:
arr2.astype(float)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15.])

In [ ]:
## 배열의 저장과 불러오기

In [ ]:

# 배열 저장하기 = np.save(파일이름, 배열이름) : .npy 형식으로 저장
# np.savez(file,array1,array2,array3....): 여러배열을 .mpz로 저장
# np.savetxt(fname,array,fmt='%d',delimiter=','):텍스트 파이로 저장
# np.savez_compressed(file,array1,array2,array3....): 압축하여 저장

In [12]:
# 매서트 체이닝 : 모듈.함수().메서드()
arr = np.arange(10)
print(arr)
arr.reshape(2, 5)
arr = np.arange(10).reshape(2, 5)
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [15]:
#배열 저장하기
np.save('array.npy', arr)


In [16]:
#배열 불러오기 - np.load()
# np.save()
# np.load('파일명')
load_arr = np.load('array.npy')
print(load_arr)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [22]:
#여러 배열 생성
arr1 = np.arange(10)
arr2 = np.arange(20).reshape(4,5)
arr3 = np.random.rand(3,3)
print(arr3)


[[0.23278785 0.73393508 0.83033842]
 [0.5617825  0.14159709 0.68767418]
 [0.08271555 0.70727792 0.50149696]]


In [36]:
np.savez('multiful_array',first_array=arr1,second_array=arr2,third_array=arr3)
#np.savez('multiful_array.npz', arr1,arr2,arr3)

In [37]:
loaded_data = np.load('multiful_array.npz')
print(loaded_data.files)

['first_array', 'second_array', 'third_array']


In [38]:
# 개별 배열 접근
arr1_loaded = loaded_data['first_array']
arr2_loaded = loaded_data['second_array']
arr3_loaded = loaded_data['third_array']



In [39]:
# 사용 후 파일 닫기
loaded_data.close()

In [40]:
# 압축 저장
np.savez_compressed('compressed_arrays', data1=arr1, data2=arr2, data3=arr3)

In [ ]:
# 경로설정
