# 배열의 생성 및 조작

In [5]:
import numpy as np

In [7]:
list1 = [1, 2, 3]
arr1 = np.array(list1)
arr2 = np.array([1, 2, 3])
print(list1)
print(arr1)
print(arr2)

[1, 2, 3]
[1 2 3]
[1 2 3]


In [17]:
#np.arange()
arr1 = np.arange(10)
print(arr1)
arr2 = np.arange(0,10,1)
print(arr2)
arr2 = np.arange(10,0,-1)
print(arr2)


[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[10  9  8  7  6  5  4  3  2  1]


In [ ]:
# np.array([1, 2, 3, 4, 5]) 생성
# np.arange(1, 6) 생성
# np.zeros(5)
# np.ones(5)
# np.linspace(0, 10, 5)
# np.random.random(5)

In [ ]:
np.ones(3)

array([1., 1., 1.])

In [20]:
np.zeros(5)
np.zeros((2, 3))
np.zeros((2, 3, 4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [23]:
#np.random.rand() - 랜덤값 배열
#0이상~1미만 사이의 무작위 수로 배열
np.random.rand(2, 3)

array([[0.9489172 , 0.49168544, 0.94535787],
       [0.4028819 , 0.23980612, 0.97408828]])

In [27]:
# np.empty()
arr = np.empty((5,2))
print(arr)


[[0.0e+000 4.9e-324]
 [9.9e-324 1.5e-323]
 [2.0e-323 2.5e-323]
 [3.0e-323 3.5e-323]
 [4.0e-323 4.4e-323]]


In [ ]:
# reshape(형태)

