In [1]:
import numpy as np

In [3]:
# 최신 표준 Generator 객체 사용법
# 1. 최신 표준 Generator 생성
rng = np.random.default_rng()

In [4]:
# 1 이상 46 미만(1~45)의 숫자 중 6개를 1차원 배열로 추출
lotto = rng.integers(1, 46, size=6)
print(lotto)  # 예: [12 45  3 24 18  7]

# 0 이상 10 미만의 정수로 채워진 2행 3열짜리 배열 생성
matrix_int = rng.integers(0, 10, size=(2, 3))
print(matrix_int)

[16 39 36  5 43 22]
[[4 4 4]
 [9 7 7]]


In [5]:
# 0.0 ~ 1.0 사이의 실수로 채워진 3행 2열 배열 생성
matrix_float = rng.random((3, 2))
print(matrix_float)

[[0.18322835 0.87806883]
 [0.84148269 0.69113138]
 [0.44538177 0.79280139]]


In [10]:
#rng.choice(a, size, replace): 샘플 추출 (복원/비복원)
#배열이나 리스트에서 무작위로 샘플을 추출합니다.
#replace=False로 설정하면 중복 없는 추출(비복원)이 가능합니다.
items = ['Apple', 'Banana', 'Orange', 'Grape']

# 중복을 허용하여 2개 선택 (기본값: replace=True)
print(rng.choice(items, size=2))

# 중복 없이 3개 선택 (비복원 추출)
print(rng.choice(items, size=3, replace=False))

['Banana' 'Apple']
['Orange' 'Banana' 'Apple']


In [11]:
#rng.shuffle(x)/rng.permutation(x): 무작위 무작위 셔플
#shuffle: 원본 배열 자체를 내부에서 직접 뒤섞어버립니다. (반환값 없음)
#permutation: 원본은 그대로 두고,뒤섞인 새로운 배열을 복사해서 반환합니다. (안전함)
arr = np.array([1, 2, 3, 4, 5])

shuffled = rng.permutation(arr)
print("원본:", arr)       # [1, 2, 3, 4, 5] 그대로 유지
print("셔플본:", shuffled) # 무작위 뒤섞인 배열

원본: [1 2 3 4 5]
셔플본: [4 3 2 5 1]


In [ ]:
arr = np.array([1, 2, 3, 4, 5])

shuffled = rng.shuffle(arr) # shuffle은 반환값이 없다.
print("원본:", arr)       # [1, 2, 3, 4, 5] 그대로 유지
print("셔플본:", shuffled) # 무작위 뒤섞인 배열

원본: [1 4 3 5 2]
셔플본: None


In [ ]:
#확률 분포 기반 난수 생성 (통계·머신러닝 필수)
NumPy random의 진가는 가우시안 표준정규분포나 균등분포 
같은 수학적 확률 분포를 따르는 데이터를 대량으로 시뮬레이션할 수 있다는 점입니다.

In [ ]:
#rng.normal(loc, scale, size): 정규 분포 (Gaussian)
#평균이loc이고 표준편차가scale인 종 모양의 정규분포 그래프를 따르는 난수 배열을 생성합니다. 
# (딥러닝 가중치 초기화 등에 필수)
# 평균 0, 표준편차 1인 표준정규분포를 따르는 데이터 10,000개 생성
normal_data = rng.normal(loc=0.0, scale=1.0, size=10000)
print(normal_data)

[-0.04189828 -0.39275827 -0.55289078 ... -1.00325825 -0.95442376
  0.20222835]


In [15]:
#rng.uniform(low, high, size): 균등 분포 (Uniform)
#지정한 범위 내의 모든 실수가 동일한 확률(균등한 빈도)로 등장하는 난수 배열을 만듭니다.
# 10.0부터 20.0 사이에서 균등한 확률로 5개 추출
uniform_data = rng.uniform(10.0, 20.0, size=5)
print(uniform_data)

[14.74215575 19.69220415 18.60001238 11.36347057 12.96016663]
