### 브리언 인덱싱
## 블리언 인텍싱의 개념

1. 원본 배열과 동일한 사이즈의 불리언 배열을 생성
2. 조건을 만족하는 인덱스에는 True,아니면 False
3. 이 불리언 배열을 인덱스로 사용하면, True위치의 값을 반환한다.


In [1]:
import numpy as np

In [ ]:
scores = [80,90,70,65,85,95,90,80,75,80]
score_arr = np.array(scores)
idx =[1,2,3,4]
print(score_arr[idx]) 

SyntaxError: cannot assign to function call here. Maybe you meant '==' instead of '='? (1662656089.py, line 4)

In [3]:
# 90점 이상인지 확인하는 불리언 배열을 생성
score_arr >=50

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [4]:
# 90점 이상만 선택
score_arr[score_arr >= 90]

array([90, 95, 90])

In [5]:
score_arr[score_arr >= 90] = 999
score_arr

array([ 80, 999,  70,  65,  85, 999, 999,  80,  75,  80])

In [10]:
# 팬시 인덱싱(fancy indexing)
arr = np.arange(20)
indices = [1,3,5,7]
print(arr[indices])
print(score_arr[indices])

[1 3 5 7]
[999  65 999  80]


In [ ]:
arr2d = np.arange(12).reshape(3,4)
print(arr2d)
print(arr2d[[0,2],[1,3]]) # arr2d(행,열)의 값을 반환

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 1 11]


In [ ]:
#넘파이 놀리연산자 : and or not
& : 그리고, | : 또는, ~ : not

In [28]:
scores = np.array([80,90,70,65,85,95,90,80,75,80])
print(scores[(scores >= 80) & (scores < 90)])

[80 85 80 80]


In [30]:
# 70점 미만 또는 95점 이상
# 배열[(조건식1) | (조건식2)]
#두 조건식 중 하나 이상 True일 경우 출력
print(scores[(scores < 70) | (scores >= 95)])

[65 95]


In [31]:
# 조건에 따른 값 치환
# np.where(조건시,참,거짓)
scores

array([80, 90, 70, 65, 85, 95, 90, 80, 75, 80])

In [33]:
# 90점 이상이면 'A', 아니면 'B'
grades = np.where(scores >= 90, 'A','B')
print(grades)

['B' 'A' 'B' 'B' 'B' 'A' 'A' 'B' 'B' 'B']


In [36]:
# 2차원 배열로 변환
# arr2d = arr1d.reshape(3,4)
# arr2d

In [40]:
# 실무 활용 예시
# 데이터 필터링
# 실제 데이터 분석에서 자주 사용되는 패턴
temperatures = np.array([22.5, 25.1, 19.8, 30.2, 28.7, 15.3, 32.1])
temperatures

array([22.5, 25.1, 19.8, 30.2, 28.7, 15.3, 32.1])

In [41]:
# 25도 이상인 날씨만 선텍
hot_days = temperatures[temperatures >= 25]
print(f'25도 이상인 날 : {hot_days}')

25도 이상인 날 : [25.1 30.2 28.7 32.1]


In [42]:
# 20도 미만인 날씨를 20도로 조정
temperatures[temperatures < 20.0] = 20
print(f'조정된 온도: {temperatures}')

조정된 온도: [22.5 25.1 20.  30.2 28.7 20.  32.1]


In [43]:
### 2차원 데이터 처리
# 성적표 데이터(학생 * 과목)
grades = np.array([
    [85, 92, 78, 90],  # 학생1
    [76, 88, 82, 79],  # 학생2
    [92, 95, 89, 94],  # 학생3
    [68, 72, 75, 71]   # 학생4
])

In [ ]:
# 각 학생의 평균 점수가 80점 이상인 학생들
# axis=1은 row(행) 방향으로 계산
# axis =0 은 column(열) 방향으로 계산
student_avg = grades.mean(axis=1)
print(student_avg)


[86.25 81.25 92.5  71.5 ]


In [46]:
#불리언 이덱싱
#배열[조건]
good_students = grades[student_avg >= 80]
print(f'평균 80점 이상 학생들의 성적 : {good_students}')

평균 80점 이상 학생들의 성적 : [[85 92 78 90]
 [76 88 82 79]
 [92 95 89 94]]


In [47]:
# 모든 과목에서 85점 이상인 점수만 추출한다.
excellent_scores = grades[grades >= 85]
print(f'85점 이상 점수들 : {excellent_scores}')

85점 이상 점수들 : [85 92 90 88 92 95 89 94]
