In [ ]:
# 배열의 연산과 변형
# 벡터화 연산 (vectorized operations)

In [1]:
import numpy as np

In [3]:
# 배열 생성
arr = np.arange(1,5)
arr

array([1, 2, 3, 4])

In [4]:
## 벡터화 연산
arr + 2

array([3, 4, 5, 6])

In [5]:
arr * 2

array([2, 4, 6, 8])

In [8]:
list = [1, 2, 3, 4]
list

[1, 2, 3, 4]

In [9]:
list * 2

[1, 2, 3, 4, 1, 2, 3, 4]

In [13]:
list + 2

TypeError: can only concatenate list (not "int") to list

In [7]:
arr1 = np.arange(5,9)
arr1

array([5, 6, 7, 8])

In [10]:
arr + arr1

array([ 6,  8, 10, 12])

In [11]:
arr * arr1

array([ 5, 12, 21, 32])

In [12]:
list1 = [5,6,7,8]
list + list1

[1, 2, 3, 4, 5, 6, 7, 8]

#주요 산술 연산 함수
#수학함수들

In [2]:
arr = np.array([1, 2, 3, 4])
print(arr)

[1 2 3 4]


In [6]:
from math import exp


print(np.square(arr)) # 제곱
print(np.sqrt(arr)) # 제곱근
print(np.exp(arr)) # 지수
print(np.log(arr)) # 로그

[ 1  4  9 16]
[1.         1.41421356 1.73205081 2.        ]
[ 2.71828183  7.3890561  20.08553692 54.59815003]
[0.         0.69314718 1.09861229 1.38629436]


In [9]:
# 배열 연산 함수들
arr1 = np.arange(5,9)
print(arr1)
print (np.add(arr,arr1))



[5 6 7 8]
[ 6  8 10 12]


In [11]:
#합계
print(np.sum(arr))
#누적합(cumulative sum)
print(np.cumsum(arr))

10
[ 1  3  6 10]


In [ ]:
# 통계함수
print(np.mean(arr)) # 평균
print(np.std(arr)) # 표준편차
print(np.var(arr)) # 분산
print(np.sqrt(np.var(arr))) # 표본분산
print(np.min(arr)) # 최솟값
print(np.max(arr)) # 최댓값
print(np.argmin(arr)) # 최솟값의 인덱스
print(np.argmax(arr)) # 최댓값의 인덱스

2.5
1.118033988749895
1.25
1.118033988749895
1
4
0
3


In [ ]:
#배열의 변형(Transformation)
### 축 변환(Transpose) : 배열이름.transpose()

In [18]:
# 2차원 배열의 축 변환
arr = np.arange(10).reshape(2, 5)
print(arr)
# 2차원 배열의 축 변환
print(arr.transpose())

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


In [19]:
# 3차원 배열의 축 변환
arr3d = np.arange(27).reshape(3, 3, 3)
print(arr3d)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [48]:
# 특정 축 순서 지정
#(0,1,2) -> (1,0,2)
print(arr3d.transpose(2, 1, 0))

[[[ 0  9 18]
  [ 3 12 21]
  [ 6 15 24]]

 [[ 1 10 19]
  [ 4 13 22]
  [ 7 16 25]]

 [[ 2 11 20]
  [ 5 14 23]
  [ 8 17 26]]]


In [ ]:
## 고급 연산 기법
# 브로드캐스팅
# shape이 다른 배열 간의 연산을 지원하는 기능

In [49]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
arr_1d = np.array([10, 20, 30])
result = arr_2d + arr_1d
print(result)

[[11 22 33]
 [14 25 36]]


In [52]:
#축지정 연산
#열 방향 합계 (axis=0)
print(np.sum(arr_2d, axis=0))
#행 방향 합계 (axis=1)
print(np.sum(arr_2d, axis=1))
#저체합
print(np.sum(arr_2d))


[5 7 9]
[ 6 15]
21


In [54]:
#조건에 따른 연산
#배열의 생성
arr = np.array([1, -2, 3, -4, 5])
print(arr)
#절대값: 양수화
print(np.abs(arr))
#조건부 연산:np.where(조건, 참일때 값, 거짓일때 값)
print(np.where(arr > 0, arr, 0))

[ 1 -2  3 -4  5]
[1 2 3 4 5]
[1 0 3 0 5]


In [ ]:
### 정규화(Normalization)

In [57]:
# 배열의 생성
data = np.array([10, 20, 30, 40, 50])
print(data)
#min/max 
normalized = (data - np.min(data)) / (np.max(data) - np.min(data))
print(normalized)

[10 20 30 40 50]
[0.   0.25 0.5  0.75 1.  ]


In [58]:
#z-score
z_score = (data - np.mean(data)) / np.std(data)
print(z_score)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [ ]:
# 이동평균계산
#배열 생성
prices = np.array([100,102,98,105,103,99,101])
print(prices)
#3일 이동평균
# np.convolve : 배열의 교차합(convolution)을 계산
# np.ones(window_size)/window_size : 윈도우 크기만큼의 평균값을 계산하기 위한 가중치 배열
# np.ones(3) -> [1,1,1]
# mode='valid' : 윈도우가 배열 범위 내에서만 계산
# mode='same' : 입력 배열과 같은 길이의 출력 배열을 반환
# mode='full' : 입력 배열과 윈도우의 모든 가능한 위치를 계산
# mode='valid'는 윈도우가 배열 범위 내에서만 계산되므로 출력 배열의 길이는 입력 배열의 길이에서 윈도우 크기를 뺀 값이 됩니다.
def moving_average(data, window_size):
    return np.convolve(data, np.ones(window_size)/window_size, mode='valid')
# 함수 호출
ma_3 = moving_average(prices, 3)
print(ma_3)

[100 102  98 105 103  99 101]
[100.         101.66666667 102.         102.33333333 101.        ]


In [60]:
def moving_average(data, window_size):
    return np.convolve(data, np.ones(window_size)/window_size, mode='full')
# 함수 호출
ma_3 = moving_average(prices, 3)
print(ma_3)

[ 33.33333333  67.33333333 100.         101.66666667 102.
 102.33333333 101.          66.66666667  33.66666667]


In [61]:
def moving_average(data, window_size):
    return np.convolve(data, np.ones(window_size)/window_size, mode='same')
# 함수 호출
ma_3 = moving_average(prices, 3)
print(ma_3)

[ 67.33333333 100.         101.66666667 102.         102.33333333
 101.          66.66666667]
